#!/usr/bin/env bash

# exit on error
set -e

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

yay -Sy --needed --noconfirm bash-completion bat eza fastfetch fd fzf man-db ripgrep starship tldr trash-cli wget zoxide

# update bat to use configured theme
bat cache --build

echo "bash-utils install complete."
