#!/usr/bin/env bash

# exit on error
set -e

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

yay -Sy --needed --noconfirm bash-completion bat eza fastfetch fzf man-db ripgrep starship tldr trash-cli zoxide

echo "bash-utils install complete."
