#!/usr/bin/env bash

# exit on error
set -e

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

yay -Sy --needed --noconfirm hyprland
yay -Sy --needed --noconfirm ghostty hyprcursor hyprpaper hyprpicker hyprpolkitagent hyprshot
yay -Sy --needed --noconfirm gimp gnome-keyring mako rofi-wayland waybar uwsm zen-browser-bin
yay -Sy --needed --noconfirm swayimg thunar thunar-archive-plugin thunar-volman tumbler viu
yay -Sy --needed --noconfirm cava pipewire pipewire-pulse pwvucontrol
yay -Sy --needed --noconfirm gtk-theme-material-black nwg-look papirus-icon-theme rose-pine-hyprcursor
yay -Sy --needed --noconfirm ttf-firacode-nerd ttf-font-awesome ttf-meslo-nerd ttf-noto-nerd 

echo "hyprland install complete."

