#!/usr/bin/env bash

# exit on error
set -e

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

yay -Sy --needed --noconfirm mesa-utils nvidia nvidia-settings nvidia-utils

echo "nvidia install complete.
