#!/usr/bin/env bash

# exit on error
set -e

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

# parsec installed for 3D modeling on a virtual/remote desktop
yay -Sy --needed --noconfirm parsec-bin superslicer-prerelease-bin

echo "superslicer install complete."
