#!/usr/bin/env bash

# Exit on error
set -e

if command -v yay &> /dev/null; then
    echo "yay is already installed."
    exit 0
fi

echo "yay not found. Installing..."

# make pacman color
sudo sed -i 's/^#\(Color\)/\1/' /etc/pacman.conf

# get dependencies
sudo pacman -Sy --needed --noconfirm base-devel git

# create temp dir for build
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

git clone https://aur.archlinux.org/yay.git "$tmp_dir"
pushd "$tmp_dir" > /dev/null

# install yay
makepkg -si --noconfirm

# clean up
popd > /dev/null

# run first use command
yay -Y --gendb

yay -S --needed --noconfirm reflector

sudo reflector --verbose -c US -p https --age 12 --latest 20 --number 10 --sort rate --save /etc/pacman.d/mirrorlist

echo "yay install complete."

