#!/usr/bin/env bash

# exit on error
set -e

if [ -z "$YURI_ENV" ]; then
    echo "YURI_ENV is not set. Exiting."
    exit 1
fi

if ! command -v yay &> /dev/null; then
    echo "yay not found. Exiting."
    exit 1
fi

yay -Sy --needed --noconfirm zram-generator

sudo cp -v "$YURI_ENV/sys_config/sddm/sddm.conf" /etc/systemd

sudo systemctl daemon-reload

sudo systemctl start systemd-zram-setup@zram0.service

zramctl # should echo zram status

echo "zram install complete."
